### ISSUE TITLE
All interruptions seem to run on a single CPU

### ISSUE THREAD

**Issue by javierbuenolopez** [Irqbalance/irqbalance#30] opened 2016-05-31 15:38 UTC
I want to balance the interruptions using irqbalance. I am using a server with 64 cores and  interruptions were being balanced properly across the first 16 cores (by default, I did not configure it before). Then I needed to use only 8 cores for them and I modified the /etc/default/irqbalance file adding:

export IRQBALANCE_BANNED_CPUS=ffffffff,ffffff00 to use only the first 8 cores.

From this moment, interruptions are behaving strangely. Randomly, when I run my application, I can see (using htop) that after a few seconds, only one core is running interruptions (CPU to 100%) and the other cores are running at 0%. The id of this core is usually 0, but not always.

Any idea ?

irqbalance version: commit dcc411e7bfdd95bbdb7fd0af8699f8cafe686ff4

Attached files:
- irqbalance_debug.txt irqbalance log. 
- lstopo  hw hierarchy
- proc_interrupts_final.txt /proc/interrupts after execution.
- proc_interrupts_initial.txt  /proc/interrupts before execution.
- smp_affinity_final.txt   /proc/irq/<i>/smp_affinity  after execution.
- smp_affinity_final.txt   /proc/irq/<i>/smp_affinity  before execution.
- where <i> represents each irq related to em50 (network interface)

[irqbalance_debug.txt](https://github.com/Irqbalance/irqbalance/files/291461/irqbalance_debug.txt)
[lstopo.txt](https://github.com/Irqbalance/irqbalance/files/291462/lstopo.txt)
[proc_interrupts_final.txt](https://github.com/Irqbalance/irqbalance/files/291463/proc_interrupts_final.txt)
[proc_interrupts_initial.txt](https://github.com/Irqbalance/irqbalance/files/291464/proc_interrupts_initial.txt)
[smp_affinity_final.txt](https://github.com/Irqbalance/irqbalance/files/291467/smp_affinity_final.txt)
[smp_affinity_initial.txt](https://github.com/Irqbalance/irqbalance/files/291469/smp_affinity_initial.txt)

**Comment by sikarash** [comment] 2016-06-01 04:35
Your system looks 16-core CPU (HyperT enabled ) x 2 sockets and the NIC is connected to
the primary socket CPU. Then the HW naturally sends its interrupts to CPU0-15 with default irqbalance setting. And you are going to restrict those irqs to CPU0-7.

Is ffffffff,ffffff00 the correct value?
I'm not sure the endian, but ffffff00,ffffffff might be the correct one. Try it.

**Comment by javierbuenolopez** [comment] 2016-06-01 07:55
No, I think ffffffff,ffffff00 is correct. First group (left), is related the cores numbered from 32 to 63 and the second one (right), from 0 to 31. Anyway, the problem is that everything seems fine (interrupts are balanced correctly ) until suddenly all seems to go to a single core. This behaviour is happening since I changed IRQBALANCE_BANNED_CPUS value for the first time. Now, this happens even irqbalance is not running. I only get to direct interruptions to a single core set in /proc/irq/\<i\>/smp_affinity_list (not when a range/list is set). I do not understand anything.

**Comment by gongleiarei** [comment] 2017-06-14 10:02
I also encountered this issue and I googled the below information:  
[](http://natsys-lab.blogspot.my/2012/09/linux-scaling-softirq-among-many-cpu.html)

So, my question is why do we using per-cpu workload as a factor in irq balance algorithm? 

Thanks!

**Comment by sbohrer** [comment] 2017-06-14 14:25
@javierbuenolopez I don't think your irqbalance_debut.txt log demonstrates your issue.  The last entry in the log shows interrupts still distributed across CPUs and load is reported as 0 for everything.  Perhaps you need to let it run longer to capture the point where all interrupts are on a single CPU.

@gongleiarei The reason per-CPU workload is considered in the algorithm is that the cost of each interrupt handler is not equal so we can't simply balance based on interrupt execution count.  When you have more CPUs than interrupts balancing is easy you just assign one to each CPU.  When you have more interrupts than CPUs, perhaps because you are restricting the allowed CPUs with IRQBALANCE_BANNED_CPUS, then you must start balancing and targeting equal load per CPU while keeping things like cache domains and NUMA locality in mind seems like the correct thing to do.

I'm not sure what is happening in this issue and I'm not sure I have time to debug and/or fix the issue, but if all interrupts end up on a single CPU and that CPU is running at a 100% while others are idle it does sound like there is a balancing bug.  Ensuring you have a debug log that has captured the issue is a good first step since it should show where irqbalance things the interrupts are assigned and what irqblance thinks the load is.

**Comment by nhorman** [comment] 2017-08-03 12:54
I agree with @sbohrer, all irqs on a single cpu sounds like a balancing but, but the debug logs don't show anything like that.  This has been open for a while, so I'll close it for now, but please reopen if you get data that demonstrates the bug

**Closed by nhorman** 2017-08-03 12:54 UTC
