### ISSUE TITLE
irqs not balancing on Lantiq VRX268 (MIPS 34Kc)

### ISSUE THREAD

**Issue by argonym** [Irqbalance/irqbalance#200] opened 2022-03-18 11:16 UTC
Hi,
IRQs don't get balanced on this hardware. Instead, all IRQs' smp affinity is reset by irqbalance back to the 1st CPU it seems.
Balancing used to work around two years ago.
Please see attached [irqbalance-debug-MIPS34Kc-VRX268.zip](https://github.com/Irqbalance/irqbalance/files/8304015/irqbalance-debug-MIPS34Kc-VRX268.zip) for /proc, /sys and dmesg.

Thank you.

```
root@LEDE:~# irqbalance --version
irqbalance version 1.8.0

root@LEDE:~# irqbalance -o -t 30 --debug
This machine seems not NUMA capable.
Isolated CPUs: 00000000
Adaptive-ticks CPUs: 00000000
Banned CPUs: 00000000
Package 0:  numa_node -1 cpu mask is 00000003 (load 0)
        Cache domain 0:  numa_node is -1 cpu mask is 00000003  (load 0) 
                CPU number 1  numa_node is -1 (load 0)
                CPU number 0  numa_node is -1 (load 0)
Adding IRQ 144 to database
Adding IRQ 7 to database
Adding IRQ 8 to database
Adding IRQ 9 to database
Adding IRQ 22 to database
Adding IRQ 23 to database
Adding IRQ 24 to database
Adding IRQ 62 to database
Adding IRQ 63 to database
Adding IRQ 72 to database
Adding IRQ 73 to database
Adding IRQ 91 to database
Adding IRQ 96 to database
Adding IRQ 112 to database
Adding IRQ 113 to database
Adding IRQ 114 to database
Adding IRQ 126 to database
Adding IRQ 127 to database
Adding IRQ 128 to database
Adding IRQ 129 to database
Adding IRQ 130 to database
Adding IRQ 131 to database
Adding IRQ 161 to database
NUMA NODE NUMBER: -1
LOCAL CPU MASK: ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff,ffffffff

-----------------------------------------------------------------------------
Package 0:  numa_node -1 cpu mask is 00000003 (load 0)
        Cache domain 0:  numa_node is -1 cpu mask is 00000003  (load 0) 
                CPU number 1  numa_node is -1 (load 0)
                CPU number 0  numa_node is -1 (load 0)
          Interrupt 144 node_num is -1 (legacy/0:5900) 
  Interrupt 73 node_num is -1 (other/0:162) 
  Interrupt 72 node_num is -1 (other/0:100) 
  Interrupt 63 node_num is -1 (other/0:1300) 
  Interrupt 62 node_num is -1 (other/0:0) 
  Interrupt 24 node_num is -1 (other/0:0) 
  Interrupt 23 node_num is -1 (other/0:0) 
  Interrupt 22 node_num is -1 (other/0:0) 
  Interrupt 9 node_num is -1 (other/0:0) 
  Interrupt 8 node_num is -1 (other/0:120) 
  Interrupt 7 node_num is -1 (other/0:6546) 
  Interrupt 126 node_num is -1 (other/0:0) 
  Interrupt 114 node_num is -1 (other/0:0) 
  Interrupt 113 node_num is -1 (other/0:0) 
  Interrupt 112 node_num is -1 (other/0:0) 
  Interrupt 96 node_num is -1 (other/0:214) 
  Interrupt 91 node_num is -1 (other/0:0) 
  Interrupt 161 node_num is -1 (other/0:0) 
  Interrupt 131 node_num is -1 (other/0:0) 
  Interrupt 130 node_num is -1 (other/0:0) 
  Interrupt 129 node_num is -1 (other/0:0) 
  Interrupt 128 node_num is -1 (other/0:0) 
  Interrupt 127 node_num is -1 (other/0:0) 
  
```

**Comment by nhorman** [comment] 2022-03-18 11:55
while it may be less than ideal, irqbalance appears to be working as designed here.  

irqbalance balances irqs based on the type of device the irq belongs to (i.e. it balances irqs to different levels based on the volume of interrupts it expects to see from that device, assigning higher volume interrupts to single cpus, while lower volume interrupts can be executed on any available cpu). It correctly identified your ath9k chip, which is on the pci bus, and identified as a high volume legacy ethernet device, and so assigned it to the level of cache_domain.  The other interrupts, based on your attached info are all platform devices, which irq has no predictive knowledge about, and so they are assigned to the cpu package level, which on your cpu means any available cpu, and because of how cpu hardware is designed, irqs then get serviced by the first non-busy cpu (which based on your cpu load, is always cpu0).

We could code in some understanding of what your platform devices are, but the real solution here is to write a policy script and have irqbalance use that (see the irqbalance man page for how policyscripts work).  

That said, it appears that it may not be necessary.  Looking at your /proc/interrupts file, most of your irq lines are quiet, and so theres not a lot of advantage (at least not in the workload snapshot you sent) in moving anything.  If you wanted to you might use a policyscript to detect mei_cpe and the xrx irqs to have a balance_level of core, rather than package, and that will balance those a little more, but other than that, I wouldn't be concerned with the current balance layout

**Comment by nhorman** [comment] 2022-05-27 17:28
closing for inactivity

**Closed by nhorman** 2022-05-27 17:28 UTC
