### ISSUE TITLE
ksoftirqd kworker locked up at 100% after small packet bursts

### ISSUE THREAD

**Issue by etcimon** [Irqbalance/irqbalance#38] opened 2017-01-27 17:32 UTC
Took me a while to figure out but once I reach ~20k PPS in rx/tx on the 10gbit/s NIC the irqbalance seems to trigger a deadlock of some kind where ksoftirqd/## show up in top with 100% cpu usage.

NIC is X540-AT2 using Pci-e x8

Seems like the Intel IXGBE driver already distributes IRQs with algorithms based on which core will be forwarded the packets. I assume the way irqbalance works currently is causing some heavy contention or deadlocks to occur with so many cores.

I'm using 2x Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz on this build with latest Fedora 25 - kernel 3.14.32

Only fix I found was to disable irqbalance and reboot. Seems to be able to reach 100k PPS easily that way.

**Comment by ppwaskie** [comment] 2017-01-28 19:13
ixgbe will attempt to distribute using the affinity_hint hook in
/proc/irq/<num>/ for each interrupt.  irqbalance will prefer that value to
apply in smp_affinity versus trying to balance the interrupt.  I have a
very hard time believing that we're causing a deadlock in the kernel, that
just makes no sense.

Two things that would be useful: 1) what version of irqbalance are you
using?  2) When this performance issue is occurring, what does the ixgbe
interrupt layout look like in /proc/interrupts?

If you disable irqbalance and reboot, then ixgbe will not be able to spread
its interrupts at all, and they'll all drop onto CPU0.  That is definitely
not ideal.

-PJ

**Comment by etcimon** [comment] 2017-01-28 19:58
I manually compiled the latest release to see if it could solve the issue but unfortunately it didn't help. The /proc/irq/ smp_affinity for eth0 is 000f,ff000fff

The IRQs did in fact go to CPU0 once I restarted. After disabling, the ksoftirqd/0 was at about 95% when doing 200k PPS and 2gbit/s TX. Otherwise, at 90mbit/s ~20kPPS all CPUs were showing 100% and only IPMI was accessible. The ksoftirqd/## was near 0% cpu otherwise and had normal behavior, it didn't progressively increase, it was fine one second and then the next, all CPUs saturated with just a slight progressive increase in traffic (seen from vnstat -i eth0 -l). The most suspicious reading in /proc/interrupts is about 1k+ timer interrupts per second. I can't really help with debugging because this is a prod server, but maybe you can reproduce on a similar system with a tool that creates small packet bursts.

**Comment by etcimon** [comment] 2017-01-28 20:12
Sorry, the TIMER reading was from /proc/softirqs, not /proc/interrupts

**Comment by etcimon** [comment] 2017-01-28 20:15
Current /proc/interrupts output at 1 day 3h of runtime:
http://pastebin.com/11Sn67Af

**Comment by etcimon** [comment] 2017-01-28 20:21
Here's a `top` reading I managed to recover from a dead putty window. The connection was lost at this tty frame

http://pastebin.com/S63H6nQB

**Comment by ppwaskie** [comment] 2017-01-28 20:51
Note that your eth0 has multiple interrupt sources (MSI-X). And your
/proc/interrupts shows everything is on CPU0.

What exactly is your workload, since it sounds like you might be running
into something else that is causing interrupt thrashing?

If you're using ixgbe, you might also benefit from using different
interrupt coalescing timing with rx-usecs through ethtool. The way these
devices work is they drop out of hardware interrupt context into soft
interrupt context, and then poll. They stay polling until there's no work
to do, and then go back to hardware interrupt context. Small packet bursts
will really mess with that, hence the suggestion to look at the interrupt
coalescing.

**Comment by etcimon** [comment] 2017-01-28 20:57
Yes, I tried increasing rx-usecs from 1 to 256 as well before disabling. My server is a simple non-blocking tcp server with 1 thread on epoll each that runs on https/http2/json and responds with 100 bytes to 1kb fairly quickly. It distributes the load by listening with multiple processes to the same address/port. My server doesn't busy loop nor file I/O, very straightforward stuff, it's been running on another server without irqbalance for 1 1/2 years. I installed this utility during migration to take advantage of the added power about 1 week ago.

**Comment by etcimon** [comment] 2017-01-28 21:14
Note that irqbalancer for me sent everything on every core, the whole grid of interrupts for MSI-X had equal amounts in them.

**Comment by etcimon** [comment] 2017-01-28 21:16
Well, not all sorry. I think it was cores 1-14 and 24-32 or so, but it was that way for all the interrupts. I remember seeing the ps aux  with ksoftirqd on those cores as well

**Comment by wirelessmundi** [comment] 2017-03-23 23:32
hi, did you figure out what was your issue? 
I'm facing a similar problem, two cpu cores get block at almost 100% which causes pkt lost. 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                        
  114 root      20   0       0      0      0 R  97.0  0.0  44:27.81 ksoftirqd/21                                                                                                                                   
    3 root      20   0       0      0      0 R  83.8  0.0  72:11.07 ksoftirqd/0

**Comment by etcimon** [comment] 2017-03-24 00:14
I has to disable the irqbalance service completely to solve this unfortunately. A single core was enough for my 10gbit lan card it seems because the driver probably assumes an efficient cpu cache

**Comment by etcimon** [comment] 2017-03-24 00:15
You will have to reboot the server to restore the default lan settings

**Comment by nhorman** [comment] 2017-08-03 14:48
I still don't believe irqbalance is causing a deadlock, thats simply not possible from user space.  At the worst irqbalance is having an issue in which in your case, it is not assigning correct smp_affinity masks

@ectimon you noted that the smp affinity mask for eth0 is 0x00ff00ff, but thats only for one queue, of which irqbalance has many (and does appear wrong, as its afining to what might be all threads within a package).  Can you tell me:

1) What is the irqbalance configuation (i.e. what options is it started with)

2) provide the output of /proc/interrupts (not in a pastebin), attached here please

3) The value of /proc/irq/<n>/smp_afinity for each irq on the system.

Thank you

**Comment by etcimon** [comment] 2017-08-03 14:57
Unfortunately this was on a $1400/mo production server which can't afford being stalled. I don't have any other means to test this, but I can say for sure that the CPU was maxing out on the IRQ kernel workers with a default fedora irqbalance setup and I saw this through IPMI

**Comment by etcimon** [comment] 2017-08-03 15:03
I remember that the interrupts & afinity didn't show anything wrong and everything was balanced from there. If I had to guess I'd say this might have had a conflict with the LAN driver's optimizations

**Comment by nhorman** [comment] 2017-08-04 11:29
I'm not sure what you mean by "Can't afford to be stalled".  I'm not asking for anything to be shutdown or reconfigured/restarted.  I'm just asking you to gather some stats and configuration from the console or over snmp. If you were able to gather the ps output to determine the existance of all those worker tasks, then this shouldn't be an issue in terms of interference with the workload.  If you are unable to gather that info though, I'm not sure how much help any of us can be.

**Comment by etcimon** [comment] 2017-08-04 19:40
TCP was stalled on the main OS but IPMI is still accessible and receives VGA input. Sorry if I can't walk you through this, the issue is here to appear on google for those who have no idea why their ksoftirqd / kworker are at 100% load, hopefully they'll have the data.

**Comment by nhorman** [comment] 2017-08-04 20:30
Um, not they won't because theres no data here, thats what I'm asking you for.  You've asserted that irqbalance has driven your cpu load to 100% and locked up your system, but you are unable to show any evidence to that effect, so we can't fix anything, and no one else will be able to solve any problems from this issue.  If you can't provide the data being asked for, I'm going to close this.  Please reopen if you can provide some information to help solve this case.

**Closed by nhorman** 2017-08-04 20:30 UTC

**Comment by etcimon** [comment] 2017-08-04 20:35
If you had answered like 8 months ago maybe the pastebin wouldn't have expired and you'd have your data. This project is buggy and this bug report is here to help people know that they need to uninstall this buggy project if they encounter this untraceable issue

**Comment by ppwaskie** [comment] 2017-08-04 20:56
There is no possible way irqbalance can or will cause the kernel softirq threads to run away.  irqbalance does *nothing* to influence how an interrupt fires or is processed in the kernel, because it's purely in userspace.  If we can't agree on that fact, then this is not going anywhere.

I'm happy to help debug, just like Neil is.  But to think that irqbalance somehow is magically breaking the kernel API and system call layer that nothing else can breach and cause a kernel thread to run away is absurd.  All irqbalance does is writes values to /proc/irq/<num>/smp_affinity, and then the IRQ core in the kernel takes over from there.  irqbalance is doing exactly what "echo <foo> > /proc/irq/<num>/smp_affinity" will do.  Nothing more.

**Comment by etcimon** [comment] 2017-08-04 21:06
Well there you have it. These values caused collisions because with irqbalance the kernel got stuck at 300mbit/s / 20k pps until I redirected the DNS, and without it can go 1gbit/s+. Why is it so difficult for you to understand that this issue exists, are you questioning my integrity? What would I have to gain about maliciously lying that this project has caused the issue?

**Comment by ppwaskie** [comment] 2017-08-04 21:26
Your previous comments are accusing irqbalance of causing the threads to peg and deadlock in the kernel.  My comment was to clarify that's not possible to cause a deadlock.  irqbalance can certainly pile interrupts onto a single CPU if the balancing criteria indicates it should.  And that's the data Neil was asking for, so we can see why it made that particular decision, if that's the thing that actually happened here.

I don't question your integrity, I'm just challenging expectations.  You reported an issue, I responded then and had asked for some additional info.  And you were looking at softirqs, which irqbalance has nothing to do with directly.  Your last responses to me in January didn't indicate to me that you still had an issue, nor were you asking anything of me.  Then you flame the devs that we're not responding and the software is crap, even though it runs in quite a few places, isn't going to be met with great responses.

If you still have the issue, like Neil asked, please gather the data to help us understand why your situation is happening and different from others.  We'd like to fix an issue if there is one.  But if you can't gather the data, then say you can't get it, and leave it at that.  You don't need to criticize something you're not helping improve at this time.

**Comment by etcimon** [comment] 2017-08-04 21:48
I gave up on this after a lot of downtime. I don't want to be flaming anyone over this but the bug report has obviously been helpful to someone else in march, it is definitely frustrating to see you sweep it under the rug with accusations of a lie or flame war, I have no expectations but the right thing to do imo is that you keep it around as a known issue for busy 48+ core servers. But then that isn't my business anymore, you'll just have to deal with the next guy and hope his A record TTL wasn't too long

**Comment by nhorman** [comment] 2017-08-04 22:11
@etcimon I do apologise for not responding sooner, bad spam filtering that I set up when I mistakenly started watching kubernetes projects got it lost for me.  That's fixed now

And no I'm not questioning your integrity, but I am asserting that you are drawing conclusions as to what the problem is here based on false assumptions and questionable observation.  And this bug did nothing to help  @wirelessmundi, as the only conclusion he could draw from it is to disable irqbalance, which leaves your irq workload distribution to the priority loading of the hardware, which can work in some cases but be catastrophic in others.

The offer for myself and the other devs to helps stands.  With proper data we can figure out what's going on, and fix anything we find to be broken.  But the vague recollection of course loads and there being "nothing wrong with the affinity values" isn't actionable information.  We need current accurate and complete data to be able to do anything of value here.

**Comment by wirelessmundi** [comment] 2017-11-29 09:21
Hi,
Sorry for the delay, but i figure out my issue was using imq and tc with hfsc qdisc to apply shapping policies, removing imq solve my issue, nothing to do with irqbalance or intel driver at least on my setup.

regards

**Comment by AlexProfi** [comment] 2019-04-02 14:51
> Hi,
> Sorry for the delay, but i figure out my issue was using imq and tc with hfsc qdisc to apply shapping policies, removing imq solve my issue, nothing to do with irqbalance or intel driver at least on my setup.
> 
> regards
Hello. How did you do this. Describe please
